apiVersion: apps/v1
kind: Deployment
metadata:
  name: dictionary-api
  namespace: dictionary
  labels:
    app: dictionary-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dictionary-api
  template:
    metadata:
      namespace: dictionary
      labels:
        app: dictionary-api
    spec:
      containers:
        - name: dictionary-api
          image: mialkin/dictionary-api:1.0.0
          ports:
            - containerPort: 80
