apiVersion: v1
kind: Service
metadata:
  name: dictionary-api
  namespace: dictionary
spec:
  selector:
    app: dictionary-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http-dictionary-api
