@baseUrl=http://localhost:2300/api

### Create new word

POST {{baseUrl}}/words/create
Content-Type: application/json

{
    "languageId": "1",
    "genderId": "2",
    "name": "apple",
    "translation": "яблоко",
    "transcription": "'æpl"
}

### List all words
GET {{baseUrl}}/words/list?languageId=1
