variables:
  DOTNET_SDK_IMAGE: mcr.microsoft.com/dotnet/sdk:8.0
  NUGET_PACKAGES_DIRECTORY: .nuget
  MIGRATIONS_DOCKER_IMAGE_NAME: mialkin/dictionary-api-migrations
  DOCKER_IMAGE_NAME: mialkin/dictionary-api

stages:
  - build
  - test
  - publish-migrations
  - publish

.restore_packages: &restore_nuget_packages
  - dotnet restore --packages $NUGET_PACKAGES_DIRECTORY

build:
  stage: build
  interruptible: true
  image: $DOTNET_SDK_IMAGE
  script:
    - *restore_nuget_packages
    - dotnet build --no-restore --configuration Release
  cache:
    key: $CI_JOB_STAGE-$CI_COMMIT_REF_SLUG
    paths:
      - $NUGET_PACKAGES_DIRECTORY

test:
  stage: test
  interruptible: true
  image: $DOTNET_SDK_IMAGE
  services:
    - name: postgres:16.1
      alias: postgres
  variables:
    POSTGRES_DB: dictionary_api
    POSTGRES_USER: dictionary_api
    POSTGRES_PASSWORD: dictionary_api
    ASPNETCORE_ENVIRONMENT: GitLab
  script:
    - *restore_nuget_packages
#    - make migrate-database
#    - https://docs.gitlab.com/ee/ci/services/
    - dotnet tool install dotnet-ef --global # TODO Create custom Docker image with dotnet tool pre-installed?
    - export PATH="$PATH:/root/.dotnet/tools"
    - dotnet ef database update --startup-project src/Dictionary.Api --project src/Dictionary.Api.Infrastructure.Implementation.Database
    - dotnet test --no-restore

publish-migrations:
  stage: publish-migrations
  interruptible: true
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker build --tag ${MIGRATIONS_DOCKER_IMAGE_NAME}:${CI_COMMIT_TAG} --file src/Dictionary.Api.Infrastructure.Implementation.Database/Dockerfile .
    - docker login --username ${DOCKER_REGISTRY_USERNAME} --password ${DOCKER_REGISTRY_PASSWORD}
    - docker push ${MIGRATIONS_DOCKER_IMAGE_NAME}:${CI_COMMIT_TAG}
    - docker logout
  rules:
    - if: $CI_COMMIT_TAG =~ /^\d+.\d+.\d+$/

publish:
  stage: publish
  interruptible: true
  image: docker:stable
  services:
    - docker:dind # Use Kaniko? https://docs.gitlab.com/ee/ci/docker/using_kaniko.html
  script:
    - docker build --tag ${DOCKER_IMAGE_NAME}:${CI_COMMIT_TAG} .
    - docker login --username ${DOCKER_REGISTRY_USERNAME} --password ${DOCKER_REGISTRY_PASSWORD}
    - docker push ${DOCKER_IMAGE_NAME}:${CI_COMMIT_TAG}
    - docker logout
  rules:
    - if: $CI_COMMIT_TAG =~ /^\d+.\d+.\d+$/

# Publish migration Docker image in the same stage in parallel
