variables:
  DOTNET_SDK_IMAGE: mcr.microsoft.com/dotnet/sdk:7.0
  NUGET_PACKAGES_DIRECTORY: .nuget
  DOCKER_IMAGE_NAME: mialkin/dictionary-api

stages:
  - build
  - test
  - publish

.restore_packages: &restore_nuget_packages
  - dotnet restore --packages $NUGET_PACKAGES_DIRECTORY

build:
  stage: build
  interruptible: true
  image: $DOTNET_SDK_IMAGE
  script:
    - *restore_nuget_packages
    - dotnet build --no-restore --configuration Release
  cache:
    key: $CI_JOB_STAGE-$CI_COMMIT_REF_SLUG
    paths:
      - $NUGET_PACKAGES_DIRECTORY
test:
  stage: test
  interruptible: true
  image: $DOTNET_SDK_IMAGE
  script:
    - *restore_nuget_packages
    - dotnet test --no-restore

publish:
  stage: publish
  interruptible: true
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker build -t ${DOCKER_IMAGE_NAME}:latest .
    - docker login --username ${DOCKER_REGISTRY_USERNAME} --password ${DOCKER_REGISTRY_PASSWORD}
    - docker push ${DOCKER_IMAGE_NAME}:latest
    - docker logout ${CI_REGISTRY}

# Publish migration Docker image in the same stage in parallel
