variables:
  DOTNET_SDK_IMAGE: mialkin/dotnet8-sdk-with-tools:1.0.0
  NUGET_PACKAGES_DIRECTORY: .nuget
  MIGRATIONS_DOCKER_IMAGE_NAME: mialkin/dictionary-api-migrations
  DOCKER_IMAGE_NAME: mialkin/dictionary-api

stages:
  - build
  - test
  - publish-migrations
  - publish

.restore_packages: &restore_nuget_packages
  - dotnet restore --packages $NUGET_PACKAGES_DIRECTORY

build:
  stage: build
  interruptible: true
  image: $DOTNET_SDK_IMAGE
  script:
    - *restore_nuget_packages
    - dotnet build --no-restore --configuration Release
  cache:
    key: $CI_JOB_STAGE-$CI_COMMIT_REF_SLUG
    paths:
      - $NUGET_PACKAGES_DIRECTORY

test:
  stage: test
  interruptible: true
  image: $DOTNET_SDK_IMAGE
  services:
    - name: postgres:16.1
      alias: postgres
    - name: redis:7.2.4
      alias: redis
  variables:
    POSTGRES_DB: dictionary_api
    POSTGRES_USER: dictionary_api
    POSTGRES_PASSWORD: dictionary_api
    ASPNETCORE_ENVIRONMENT: GitLab
    ALLOW_EMPTY_PASSWORD: "yes" # Redis
  script:
    - *restore_nuget_packages
    - make update-database
    - dotnet test --no-restore

publish-migrations:
  stage: publish-migrations
  interruptible: true
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker build
      --tag ${MIGRATIONS_DOCKER_IMAGE_NAME}:${CI_COMMIT_TAG}
      --file src/Dictionary.Api.Infrastructure.Implementation.Database/Dockerfile .
    - docker login --username ${DOCKER_REGISTRY_USERNAME} --password ${DOCKER_REGISTRY_PASSWORD}
    - docker push ${MIGRATIONS_DOCKER_IMAGE_NAME}:${CI_COMMIT_TAG}
    - docker logout
  rules:
    - if: $CI_COMMIT_TAG =~ /^\d+.\d+.\d+$/

publish:
  stage: publish
  interruptible: true
  image: docker:stable
  services:
    - docker:dind # Use Kaniko? https://docs.gitlab.com/ee/ci/docker/using_kaniko.html
  script:
    - docker build --tag ${DOCKER_IMAGE_NAME}:${CI_COMMIT_TAG} .
    - docker login --username ${DOCKER_REGISTRY_USERNAME} --password ${DOCKER_REGISTRY_PASSWORD}
    - docker push ${DOCKER_IMAGE_NAME}:${CI_COMMIT_TAG}
    - docker logout
  rules:
    - if: $CI_COMMIT_TAG =~ /^\d+.\d+.\d+$/

# TODO Publish migration Docker image in the same stage in parallel
