variables:
  DOTNET_SDK_IMAGE: mcr.microsoft.com/dotnet/sdk:7.0
  NUGET_PACKAGES_DIRECTORY: .nuget

stages:
  - build
  - test
  - deploy

build:
  stage: build
  interruptible: true # https://docs.gitlab.com/ee/ci/yaml/#interruptible
  image: $DOTNET_SDK_IMAGE
  script:
    - dotnet restore --packages $NUGET_PACKAGES_DIRECTORY
    - dotnet build --no-restore --configuration Release
  cache:
    key: $CI_JOB_STAGE-$CI_COMMIT_REF_SLUG
    paths:
      - $NUGET_PACKAGES_DIRECTORY
test:
  stage: test
  interruptible: true
  image: $DOTNET_SDK_IMAGE
  script:
    - dotnet restore --packages $NUGET_PACKAGES_DIRECTORY
    - dotnet test --no-restore

deploy:
  stage: deploy
  script:
    - echo "Deploying..." # Consider using GitOps with Helm charts or something similar. https://about.gitlab.com/topics/gitops/
