variables:
  DOTNET_SDK_IMAGE: mcr.microsoft.com/dotnet/sdk:7.0
  NUGET_PACKAGES_DIRECTORY: .nuget
  DOCKER_IMAGE_NAME: mialkin/dictionary-api

stages:
  - build
  - test
  - publish

.restore_packages: &restore_nuget_packages
  - dotnet restore --packages $NUGET_PACKAGES_DIRECTORY

build:
  stage: build
  interruptible: true # https://docs.gitlab.com/ee/ci/yaml/#interruptible
  image: $DOTNET_SDK_IMAGE
  script:
    - *restore_nuget_packages
    - dotnet build --no-restore --configuration Release
  cache:
    key: $CI_JOB_STAGE-$CI_COMMIT_REF_SLUG
    paths:
      - $NUGET_PACKAGES_DIRECTORY
test:
  stage: test
  interruptible: true
  image: $DOTNET_SDK_IMAGE
  script:
    - *restore_nuget_packages
    - dotnet test --no-restore

publish:
  stage: publish
  script:
    - docker build -t ${DOCKER_IMAGE_NAME}:latest .
#    - docker login ${CI_REGISTRY} -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD}
#    - docker push ${DOCKER_IMAGE_NAME}:latest
#    - docker logout ${CI_REGISTRY}

# https://stackoverflow.com/questions/45517733/how-to-publish-docker-images-to-docker-hub-from-gitlab-ci
