variables:
  DOTNET_SDK_IMAGE: mcr.microsoft.com/dotnet/sdk:7.0

stages:
  - build
  - test
  - deploy

build:
  stage: build
  interruptible: true # https://docs.gitlab.com/ee/ci/yaml/#interruptible
  image: $DOTNET_SDK_IMAGE
  script:
    - echo "Building..."

test:
  stage: test
  interruptible: true
  script:
    - echo "Testing..."

deploy:
  stage: deploy
  script:
    - echo "Deploying..." # Consider using GitOps with Helm charts or something similar. https://about.gitlab.com/topics/gitops/
