version: "3.9"

services:
  postgres:
    image: postgres:16.1
    container_name: dictionary-api-postgres
    environment:
      POSTGRES_DB: dictionary_api
      POSTGRES_USER: dictionary_api
      POSTGRES_PASSWORD: dictionary_api
    ports:
      - ${POSTGRES_PORT}:5432
