@baseUrl=http://localhost:2300/api
@authCookieName = Dictionary.Session
@authCookieValue = <authCookieValue>

### Create new word

POST {{baseUrl}}/words/create
Cookie: {{authCookieName}}={{authCookieValue}}
Content-Type: application/json

{
    "languageId": "1",
    "genderId": "2",
    "name": "apple",
    "translation": "яблоко",
    "transcription": "'æpl"
}

### Search words
GET {{baseUrl}}/words/search?languageId=1
Cookie: {{authCookieName}}={{authCookieValue}}
